version: "3.2"
services:
  client:
    image: nginx
    ports:
      - 8000:8000
    volumes:
      - ./public/:/usr/share/nginx/html
    environment:
      NGINX_PORT: 8000
  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    command:
      - --api.dashboard
      - --providers.docker=true
    labels:
      - traefik.http.routers.traefik.rule=Host(`localhost`)
      - traefik.http.routers.traefik.service=api@internal
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
        - 15692:15692
    volumes:
      - ./rabbitmq/:/etc/rabbitmq/
    healthcheck:
        test: rabbitmq-diagnostics -q ping
        interval: 30s
        timeout: 30s
        retries: 3
    networks:
        - sse-wss-polling-network
  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: mongo
    expose:
      - 27017
    command: --replSet my-test --bind_ip_all
    ports:
      - 27017:27017
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
    networks:
      - sse-wss-polling-network
  mongo2:
    hostname: mongo2
    container_name: mongo2
    image: mongo
    expose:
      - 27017
    command: --replSet my-test --bind_ip_all
    ports:
      - 27018:27017
    networks:
      - sse-wss-polling-network
  mongo3:
      hostname: mongo3
      container_name: mongo3
      image: mongo
      expose:
        - 27017
      command: --replSet my-test --bind_ip_all
      ports:
        - 27019:27017
      networks:
        - sse-wss-polling-network
  mongodb-exporter:
      image: docker.io/bitnami/mongodb-exporter
      container_name: mongodb-exporter
      command: '--mongodb.direct-connect=false'
      environment:
          MONGODB_URI:  'mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=my-test'
      ports:
        - 9216:9216
      networks:
        - sse-wss-polling-network
      depends_on:
        - mongo1
        - mongo2
        - mongo3
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    ports:
      - 9100:9100
    networks:
      - sse-wss-polling-network
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8098:8098
    command:
      - '-port=8098'
    networks:
      - sse-wss-polling-network
  grafana:
    image: grafana/grafana-enterprise:8.2.0
    container_name: grafana
    ports:
      - 3000:3000
    user: '472'
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - sse-wss-polling-network
    depends_on:
      - prometheus
  prometheus:
      image: prom/prometheus
      container_name: prometheus
      volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        - ./prometheus/alert.rules:/etc/prometheus/alert.rules
      ports:
        - 9090:9090
      networks:
        - sse-wss-polling-network
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - 9093:9093
    networks:
      - sse-wss-polling-network
  order-ms:
    build: ./order-ms
    container_name: order-ms
    ports: 
      - 3001:3001
    depends_on:
        mongo1:
          condition: service_healthy
        rabbitmq:
          condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      MONGODB_URL: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=my-test
      PORT: 3001
    labels:
      - traefik.http.routers.order-ms.rule=Host(`localhost`) && Path(`/order-ms`)
      - traefik.http.services.service.loadbalancer.server.port=3001
    networks:
        - sse-wss-polling-network
  polling-notification:
    build: ./polling-notification
    container_name: polling-notification
    ports: 
      - 3002:3002
    depends_on:
        mongo1:
          condition: service_healthy
    environment:
      MONGODB_URL: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=my-test
      PORT: 3002
    networks:
        - sse-wss-polling-network
  sse-notification:
    build: ./sse-notification
    container_name: sse-notification
    ports: 
      - 3003:3003
    depends_on:
        mongo1:
          condition: service_healthy
    environment:
      MONGODB_URL: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=my-test
      PORT: 3003
    networks:
        - sse-wss-polling-network
  wss-notification:
    build: ./wss-notification
    container_name: wss-notification
    ports: 
      - 3004:3004
      - 8090:8090
    depends_on:
        rabbitmq:
          condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      PORT: 3004
      WSS_PORT: 8090
    networks:
        - sse-wss-polling-network
networks:
  sse-wss-polling-network:
    driver: bridge
