global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'my-project'
rule_files:
  - 'alert.rules'
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8098']
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'mongodb-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['mongodb-exporter:9216']
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']
  - job_name: 'rabbitmq-exporter'
    static_configs:
      - targets: ['rabbitmq:15692']
  - job_name: 'microservices'
    static_configs:
      - targets: ['order-ms:3001', 'polling-notification:3002', 'sse-notification:3003', 'wss-notification:3004']
  
